import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Samsung Galaxy S23 AMOLED Display",
    model: "Galaxy S23",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-S911B-AMOLED-BLK",
    description:
      "Original replacement AMOLED display for Samsung Galaxy S23. High quality screen with vibrant colors and excellent touch response.",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p2",
    name: "Samsung Galaxy S22 LCD Screen",
    model: "Galaxy S22",
    category: "LCD",
    color: "White",
    partNumber: "SM-S901B-LCD-WHT",
    description: "Replacement LCD screen for Samsung Galaxy S22. Perfect fit and factory quality display.",
    price: 149.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p3",
    name: "Samsung Galaxy Note 20 AMOLED Display",
    model: "Galaxy Note 20",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-N980F-AMOLED-BLK",
    description:
      "Original Samsung Galaxy Note 20 AMOLED display with S-Pen digitizer. Perfect for repairs or replacements.",
    price: 229.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p4",
    name: "Samsung Galaxy A53 LCD Screen",
    model: "Galaxy A53",
    category: "LCD",
    color: "Blue",
    partNumber: "SM-A536B-LCD-BLU",
    description: "Replacement LCD screen for Samsung Galaxy A53. Includes digitizer and front glass.",
    price: 99.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p5",
    name: "Samsung Galaxy S21 AMOLED Display",
    model: "Galaxy S21",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-G991B-AMOLED-BLK",
    description:
      "High-quality AMOLED replacement display for Samsung Galaxy S21. Factory calibrated for perfect color reproduction.",
    price: 179.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p6",
    name: "Samsung Galaxy S22 AMOLED Display",
    model: "Galaxy S22",
    category: "AMOLED",
    color: "White",
    partNumber: "SM-S901B-AMOLED-WHT",
    description: "Premium AMOLED display for Samsung Galaxy S22. Includes digitizer and front glass assembly.",
    price: 189.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p7",
    name: "Samsung Galaxy S23 LCD Screen",
    model: "Galaxy S23",
    category: "LCD",
    color: "Black",
    partNumber: "SM-S911B-LCD-BLK",
    description: "Budget-friendly LCD replacement screen for Samsung Galaxy S23. Great alternative to AMOLED displays.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p8",
    name: "Samsung Galaxy Note 20 LCD Screen",
    model: "Galaxy Note 20",
    category: "LCD",
    color: "Blue",
    partNumber: "SM-N980F-LCD-BLU",
    description: "LCD replacement screen for Samsung Galaxy Note 20. Includes digitizer and S-Pen compatibility.",
    price: 159.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p9",
    name: "Samsung Galaxy A53 AMOLED Display",
    model: "Galaxy A53",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-A536B-AMOLED-BLK",
    description: "Premium AMOLED upgrade for Samsung Galaxy A53. Better colors and contrast than the original LCD.",
    price: 149.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p10",
    name: "Samsung Galaxy S21 LCD Screen",
    model: "Galaxy S21",
    category: "LCD",
    color: "White",
    partNumber: "SM-G991B-LCD-WHT",
    description:
      "Cost-effective LCD replacement for Samsung Galaxy S21. Good alternative to more expensive AMOLED displays.",
    price: 119.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p11",
    name: "Samsung Galaxy S22 Ultra AMOLED Display",
    model: "Galaxy S22",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-S908B-AMOLED-BLK",
    description:
      "Ultra high resolution AMOLED display for Samsung Galaxy S22. Premium quality with perfect color accuracy.",
    price: 249.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p12",
    name: "Samsung Galaxy S23 Plus AMOLED Display",
    model: "Galaxy S23",
    category: "AMOLED",
    color: "Green",
    partNumber: "SM-S916B-AMOLED-GRN",
    description:
      "Larger AMOLED display for Samsung Galaxy S23 Plus. Factory original quality with excellent brightness.",
    price: 229.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p13",
    name: "Samsung Galaxy Note 20 Ultra AMOLED Display",
    model: "Galaxy Note 20",
    category: "AMOLED",
    color: "Black",
    partNumber: "SM-N985F-AMOLED-BLK",
    description:
      "Premium Ultra AMOLED display for Samsung Galaxy Note 20 Ultra. Includes S-Pen digitizer and front glass.",
    price: 279.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p14",
    name: "Samsung Galaxy A53 5G LCD Screen",
    model: "Galaxy A53",
    category: "LCD",
    color: "White",
    partNumber: "SM-A536B-LCD-WHT-5G",
    description:
      "Replacement LCD screen specifically for the 5G version of Samsung Galaxy A53. Complete assembly with frame.",
    price: 109.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p15",
    name: "Samsung Galaxy S21 FE AMOLED Display",
    model: "Galaxy S21",
    category: "AMOLED",
    color: "Red",
    partNumber: "SM-G990B-AMOLED-RED",
    description:
      "AMOLED display replacement for Samsung Galaxy S21 FE (Fan Edition). High quality with excellent touch response.",
    price: 169.99,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "p16",
    name: "Samsung Galaxy S22 Plus LCD Screen",
    model: "Galaxy S22",
    category: "LCD",
    color: "Black",
    partNumber: "SM-S906B-LCD-BLK",
    description: "Large LCD replacement screen for Samsung Galaxy S22 Plus. Budget-friendly alternative to AMOLED.",
    price: 139.99,
    image: "/placeholder.svg?height=400&width=400",
  },
]

