import type { Order } from "./types"
import { mockProducts } from "./mock-data"

export const mockOrders: Order[] = [
  {
    id: "order1",
    userId: "user1",
    items: [
      {
        product: mockProducts[0],
        quantity: 1,
        price: mockProducts[0].price,
      },
      {
        product: mockProducts[2],
        quantity: 2,
        price: mockProducts[2].price,
      },
    ],
    total: mockProducts[0].price + mockProducts[2].price * 2,
    status: "delivered",
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-01-18T14:20:00Z",
    shippingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    billingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    paymentMethod: "Credit Card",
    trackingNumber: "TRK12345678",
    shippedAt: "2023-01-16T09:15:00Z",
    deliveredAt: "2023-01-18T14:20:00Z",
  },
  {
    id: "order2",
    userId: "user1",
    items: [
      {
        product: mockProducts[1],
        quantity: 1,
        price: mockProducts[1].price,
      },
    ],
    total: mockProducts[1].price,
    status: "shipped",
    createdAt: "2023-02-20T15:45:00Z",
    updatedAt: "2023-02-21T11:30:00Z",
    shippingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    billingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    paymentMethod: "PayPal",
    trackingNumber: "TRK87654321",
    shippedAt: "2023-02-21T11:30:00Z",
  },
  {
    id: "order3",
    userId: "user1",
    items: [
      {
        product: mockProducts[3],
        quantity: 1,
        price: mockProducts[3].price,
      },
      {
        product: mockProducts[5],
        quantity: 1,
        price: mockProducts[5].price,
      },
    ],
    total: mockProducts[3].price + mockProducts[5].price,
    status: "processing",
    createdAt: "2023-03-10T09:20:00Z",
    updatedAt: "2023-03-10T14:15:00Z",
    shippingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    billingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
      phone: "555-123-4567",
    },
    paymentMethod: "Credit Card",
  },
  {
    id: "order4",
    userId: "user2",
    items: [
      {
        product: mockProducts[7],
        quantity: 2,
        price: mockProducts[7].price,
      },
    ],
    total: mockProducts[7].price * 2,
    status: "pending",
    createdAt: "2023-03-15T16:30:00Z",
    updatedAt: "2023-03-15T16:30:00Z",
    shippingAddress: {
      fullName: "Jane Smith",
      addressLine1: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      postalCode: "90001",
      country: "USA",
      phone: "555-987-6543",
    },
    billingAddress: {
      fullName: "Jane Smith",
      addressLine1: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      postalCode: "90001",
      country: "USA",
      phone: "555-987-6543",
    },
    paymentMethod: "Credit Card",
  },
]

